version: "3.7"

services:

  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    networks:
      - hydra_network
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
      
networks:
  hydra_network:
    driver: bridge
    name: hydra_oidc_network
