version: '3.7'

services:

  hydra:
    image: oryd/hydra:latest
    container_name: hydra
    depends_on:
      - hydra-migrate
    ports:
      - "9000:4444" # Public port
      - "9001:4445" # Admin port
    networks:
      - hydra_network
    command:
      serve all
    environment:
      - URLS_SELF_ISSUER=https://dev.api.vidchain.net
      - URLS_CONSENT=http://host.docker.internal:3000/consent
      - URLS_LOGIN=http://host.docker.internal:3000/login
      - URLS_LOGOUT=http://host.docker.internal:3000/logout
      - SERVE_COOKIES_SAME_SITE_MODE=Strict
      # - OAUTH2_ERROR_URL. This URL can be used to provide an endpoint which will receive error messages from ORY Hydra that should be displayed to the end user.
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=T68zLmRJonSNbRUWRlqOFFJWBLXU7yrn
      - CORS_ENABLED=true
      - CORS_ALLOWED_ORIGINS=*
      - CORS_DEBUG=true
    restart: unless-stopped

  hydra-migrate:
    image: oryd/hydra:latest
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    networks:
      - hydra_network
    command:
      migrate sql -e --yes
    restart: on-failure

networks:
  hydra_network:
    driver: bridge
    name: hydra_oidc_network
