apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra
  labels:
    app: hydra
spec:
  selector:
    matchLabels:
      app: hydra
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: hydra
    spec:
      containers:
      - name: hydra
        image: oryd/hydra:latest
        command: ["hydra"]
        args: ["serve", "all"]
        ports:
        - containerPort: 4444
        - containerPort: 4445
        env:
          - name: URLS_SELF_ISSUER
            valueFrom:
              configMapKeyRef:
                name: hydra-configmap
                key: URLS_SELF_ISSUER
          - name: URLS_CONSENT
            valueFrom:
              configMapKeyRef:
                name: hydra-configmap
                key: URLS_CONSENT
          - name: URLS_LOGIN
            valueFrom:
              configMapKeyRef:
                name: hydra-configmap
                key: URLS_LOGIN
          - name: URLS_LOGOUT
            valueFrom:
              configMapKeyRef:
                name: hydra-configmap
                key: URLS_LOGOUT
          - name: SERVE_COOKIES_SAME_SITE_MODE
            valueFrom:
              configMapKeyRef:
                name: hydra-configmap
                key: SERVE_COOKIES_SAME_SITE_MODE
          - name: CORS_ENABLED
            valueFrom:
              configMapKeyRef:
                name: hydra-configmap
                key: CORS_ENABLED
          - name: CORS_ALLOWED_ORIGINS
            valueFrom:
              configMapKeyRef:
                name: hydra-configmap
                key: CORS_ALLOWED_ORIGINS
          - name: CORS_DEBUG
            valueFrom:
              configMapKeyRef:
                name: hydra-configmap
                key: CORS_DEBUG
          - name: HTTPS_ALLOW_TERMINATION_FROM
            valueFrom:
              configMapKeyRef:
                name: hydra-configmap
                key: HTTPS_ALLOW_TERMINATION_FROM
          - name: WEBFINGER_OIDC_DISCOVERY_SUPPORTED_SCOPE
            valueFrom:
              configMapKeyRef:
                name: hydra-configmap
                key: WEBFINGER_OIDC_DISCOVERY_SUPPORTED_SCOPE
          - name: DSN
            valueFrom:
              secretKeyRef:
                name: hydra
                key: postgres-endpoint
          - name: SECRETS_SYSTEM
            valueFrom:
              secretKeyRef:
                name: hydra
                key: secrets-system

---

apiVersion: batch/v1
kind: Job
metadata:
  name: hydra-migrate
spec:
  template:
    spec:
      containers:
      - name: hydra-migrate
        image: oryd/hydra:latest
        args: ["migrate", "sql", "-e", "--yes"]
        env:
          - name: DSN
            valueFrom:
              secretKeyRef:
                name: hydra
                key: postgres-endpoint
      restartPolicy: Never
  backoffLimit: 4
   
---

apiVersion: v1
kind: Service
metadata:
  name: hydra
  labels:
    app: hydra
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 4444
  - name: "9001"
    port: 9001
    targetPort: 4445
  selector:
    app: hydra

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hydra-ingress
  namespace: development
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/auth-proxy-set-headers: custom-headers
spec:
  tls:
  - hosts:
    - dev.vidchain.net
    secretName: tls-secret-development
  rules:
  - host: dev.vidchain.net
    http:
      paths:
      - path: /oauth2
        backend:
          serviceName: hydra
          servicePort: 9000
      - path: /clients
        backend:
          serviceName: hydra
          servicePort: 9001
      - path: /.well-known/openid-configuration
        backend:
          serviceName: hydra
          servicePort: 9000
      - path: /.well-known/jwks.json
        backend:
          serviceName: hydra
          servicePort: 9000


--- 

apiVersion: v1
data:
  X-Forwarded-Proto: "https"
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: development