version: "3.7"

services:

  identity-consent-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: vidchain/identity-consent-api:v0.1
    container_name: identity-consent-api
    depends_on:
      - redis
    restart: always
    logging:
      options:
        max-size: "100m"
        max-file: "50"
    ports:
      - 3000:3000
    networks:
      - hydra_network
    environment:
      - REDIS_URL=redis
      - BASE_URL=https://dev.api.vidchain.net
      - PORT=3000
      - REDIS_PORT=6379
      - HYDRA_URL=http://hydra:4445
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - hydra_network
  
 

networks:
  hydra_network:
    driver: bridge
    name: hydra_oidc_network
